"""Immutable foundation schema snapshot; do not import runtime models."""

import sqlalchemy as sa
from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("policy_status", sa.String(length=30), nullable=False),
        sa.Column("collection_method", sa.String(length=80), nullable=False),
        sa.Column("policy_reference", sa.String(length=500), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.CheckConstraint("retention_days IS NULL OR retention_days > 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("request_key", sa.String(length=120), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("adapter_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.CheckConstraint("status IN ('RUNNING','COMPLETED','PARTIAL','FAILED')"),
        sa.CheckConstraint("accepted = inserted + duplicates"),
        sa.CheckConstraint("fetched = accepted + rejected"),
        sa.CheckConstraint(
            "fetched >= 0 AND accepted >= 0 AND inserted >= 0 AND duplicates >= 0 AND rejected >= 0"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "request_key"),
    )
    op.create_table(
        "raw_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("source_job_id", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_job_id", "content_hash"),
    )
    op.create_table(
        "rejections",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "ordinal"),
    )
    op.create_table(
        "observations",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("raw_job_id", sa.String(length=36), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_job_id"],
            ["raw_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "ordinal"),
    )
    op.create_index(
        op.f("ix_observations_raw_job_id"), "observations", ["raw_job_id"], unique=False
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE FUNCTION reject_raw_mutation() "
            "RETURNS trigger LANGUAGE plpgsql AS $$ "
            "BEGIN RAISE EXCEPTION 'raw_jobs is immutable'; END; $$"
        )
        op.execute(
            "CREATE TRIGGER raw_immutable BEFORE UPDATE OR DELETE ON raw_jobs "
            "FOR EACH ROW EXECUTE FUNCTION reject_raw_mutation()"
        )
    else:
        op.execute(
            "CREATE TRIGGER raw_no_update BEFORE UPDATE ON raw_jobs "
            "BEGIN SELECT RAISE(ABORT, 'raw_jobs is immutable'); END"
        )
        op.execute(
            "CREATE TRIGGER raw_no_delete BEFORE DELETE ON raw_jobs "
            "BEGIN SELECT RAISE(ABORT, 'raw_jobs is immutable'); END"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_raw_job_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_table("rejections")
    op.drop_table("raw_jobs")
    op.drop_table("ingestion_runs")
    op.drop_table("sources")
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION reject_raw_mutation()")
